project:
  type: default
#  output-dir: out
  execute-dir: project   # force working dir to project root

filters:
  - _quarto.lua

format:
  html:
    toc: true
    number-sections: true
    code-fold: false
